//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioAnotherGBDesire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioAnotherGBDesire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioAnotherGBDesire", typeof(ScenarioAnotherGBDesire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Anesan&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Anesan&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち普通１&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Anesan {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Childhood&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Childhood&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Childhood {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Cool&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T_Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Cool {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Cunning&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Cunning&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Cunning&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Cunning&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Cunning {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Cunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Curtness&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Curtness&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;agbd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Curtness {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Dame&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T_Da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Dame {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Devilish&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Devilish&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Devilish {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Friendly&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Friendly&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち口元に手を当てる&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Friendly {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Genki&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Genki&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Genki {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Gyaru&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Gyaru&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Gyaru&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Gyaru&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Gyaru {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Gyaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Ladylike&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Ladylike&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Ladylike {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Majime&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Majime&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Majime {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Masochist&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Masochist&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Masochist&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Masochist&quot;: {
        ///    &quot;ID&quot;: &quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Masochist {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Missy&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Missy&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Missy {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Muku&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T_Muk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Muku {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Pride&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Pride&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Pride {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Pure&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_T_Pur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Pure {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Rindere&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Rindere&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Rindere {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Sadist&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Sadist&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち考える&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Sadist {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Secretary&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Secretary&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち腕を組む&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Secretary {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Silent&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Silent&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Silent {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Sister&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Sister&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;疑問&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち頬掻き&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Sister {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_intro_0020_M_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_intro_0020_M_Yandere&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_intro_0020_T_Yandere&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;にっこり&quot;,
        ///        &quot;MotionInfo&quot;: {
        ///          &quot;ScriptFile&quot;: &quot;h_kaiwa_tati_001.ks&quot;,
        ///          &quot;ScriptLabel&quot;: &quot;*会話立ち普通１&quot;
        ///        }
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;agbd_intro_0020_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADV_Yandere {
            get {
                return ResourceManager.GetString("AnotherGBDesireADV_Yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd0001&quot;: {
        ///    &quot;ID&quot;: &quot;agbd0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_init_chara&quot;
        ///  },
        ///
        ///  &quot;agbd_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_init_hide_men&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: false,
        ///      &quot;ManRequired&quot;: 32,
        ///      &quot;ValidManType&quot;: [
        ///        &quot;YoungMan&quot;,
        ///        &quot;Yanki&quot;,
        ///        &quot;MiddleAged&quot;,
        ///        &quot;Otaku&quot;
        ///      ],
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADVIntro {
            get {
                return ResourceManager.GetString("AnotherGBDesireADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;agbd_phase2_init&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase2_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase2_init_a&quot;
        ///  },
        ///
        ///  &quot;agbd_phase2_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase2_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase2_init_b&quot;
        ///  },
        ///
        ///  &quot;agbd_phase2_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase2_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase2_init_c&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADVPhase2 {
            get {
                return ResourceManager.GetString("AnotherGBDesireADVPhase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_phase3_init&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase3_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase3_init_a&quot;
        ///  },
        ///
        ///  &quot;agbd_phase3_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase3_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase3_init_b&quot;
        ///  },
        ///
        ///  &quot;agbd_phase3_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_phase3_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_phase3_init_c&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADVPhase3 {
            get {
                return ResourceManager.GetString("AnotherGBDesireADVPhase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;agbd_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_postyotogi_init_a&quot;
        ///  },
        ///
        ///  &quot;agbd_postyotogi_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_postyotogi_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM019.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;agbd_postyotogi_init_b&quot;
        ///  },
        ///
        ///  &quot;agbd_postyotogi_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;agbd_postyotogi_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnotherGBDesireADVPostYotogi {
            get {
                return ResourceManager.GetString("AnotherGBDesireADVPostYotogi", resourceCulture);
            }
        }
    }
}
