//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioLustfulMaid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioLustfulMaid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioLustfulMaid", typeof(ScenarioLustfulMaid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lum_intro_0020_M_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;lum_intro_0020_M_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Chara&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;WaitFullLoad&quot;: true,
        ///    &quot;NextStepID&quot;: &quot;lum_intro_0020_T_Muku&quot;,
        ///    &quot;CharaData&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;F&quot;,
        ///        &quot;UseBranchIndex&quot;: true,
        ///        &quot;Visible&quot;: true,
        ///        &quot;WaitLoad&quot;: true,
        ///        &quot;FaceAnime&quot;: &quot;にっこり&quot;
        ///      }
        ///    ]
        ///  },
        ///
        ///  &quot;lum_intro_0020_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;lum_intro_0020_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LustfulMaidADV_Muku {
            get {
                return ResourceManager.GetString("LustfulMaidADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lum0001&quot;: {
        ///    &quot;ID&quot;: &quot;lum0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;MyRoom&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lum0001_init_chara&quot;
        ///  },
        ///
        ///  &quot;lum0001_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;lum0001_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lum_intro_0001&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;IsClubOwnerMainCharacter&quot;: true,
        ///      &quot;ManRequired&quot;: 0,
        ///      &quot;ValidManType&quot;: [
        ///        &quot;YoungMan&quot;
        ///      ],
        ///      &quot;NPC&quot;: [
        ///        {
        ///          &quot;Index&quot;: 0,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LustfulMaidADVIntro {
            get {
                return ResourceManager.GetString("LustfulMaidADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_postyotogi_init_a&quot;
        ///  },
        ///
        ///  &quot;imvi_postyotogi_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_postyotogi_init_b&quot;
        ///  },
        ///
        ///  &quot;imvi_postyotogi_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LustfulMaidADVPostYotogi {
            get {
                return ResourceManager.GetString("LustfulMaidADVPostYotogi", resourceCulture);
            }
        }
    }
}
