//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioExpExchangeEvent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioExpExchangeEvent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioExpExchangeEvent", typeof(ScenarioExpExchangeEvent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;eee0001&quot;: {
        ///    &quot;ID&quot;: &quot;eee0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;eee0001_init_chara&quot;
        ///  },
        ///
        ///  &quot;eee0001_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;eee0001_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;eee0001_init_hide_men&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: false,
        ///      &quot;ManRequired&quot;: 35,
        ///      &quot;ValidManType&quot;: [
        ///        {
        ///          &quot;Type&quot;: [
        ///            &quot;YoungMan&quot;,
        ///            &quot;MiddleAged&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpChangeEventADVIntro {
            get {
                return ResourceManager.GetString("ExpChangeEventADVIntro", resourceCulture);
            }
        }
    }
}
