//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioManInLilies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioManInLilies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioManInLilies", typeof(ScenarioManInLilies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Muku&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Muku&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Muku {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil0001&quot;: {
        ///    &quot;ID&quot;: &quot;mil0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_init_chara&quot;
        ///  },
        ///
        ///  &quot;mil_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;mil_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_init_hide_pairedmen&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;ManRequired&quot;: 0,
        ///      &quot;RequiresMaidPairMan&quot;: true,
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: true
        ///    }
        ///  },
        ///
        ///  &quot;mil_init_hide_pairedmen&quot;: {
        ///    &quot;ID&quot;: &quot;mil_init_hide_pairedmen&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADVIntro {
            get {
                return ResourceManager.GetString("ManInLiliesADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;lbp_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;hgbc_postyotogi_remove_owner&quot;
        ///  },
        ///
        ///  &quot;hgbc_postyotogi_remove_owner&quot;: {
        ///    &quot;ID&quot;: &quot;hgbc_postyotogi_remove_owner&quot;,
        ///    &quot;Type&quot;: &quot;ListUpdate&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;WaitFullLoad&quot;: true,
        ///    &quot;NextStepID&quot;: &quot;lbp_postyotogi_init_a&quot;,
        ///    &quot;ListUpdateData&quot;: {
        ///      &quot;Remove&quot;: [
        ///        {
        ///          &quot;Type&quot;: &quot;Owner&quot;,
        ///          &quot;SrcPosition&quot;: 0
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADVPostYotogi {
            get {
                return ResourceManager.GetString("ManInLiliesADVPostYotogi", resourceCulture);
            }
        }
    }
}
