//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioImmoralVillage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioImmoralVillage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioImmoralVillage", typeof(ScenarioImmoralVillage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Anesan&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Anesan&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Anesan&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Anesan {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Childhood&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Childhood&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Chi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Childhood {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cool&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Cool {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Curtness&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Curtness&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Curtnes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Curtness {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Dame&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Dame {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Devilish&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Devilish&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Devilis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Devilish {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Friendly&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Friendly&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Friendl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Friendly {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Genki&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Genki&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Genki&quot;,
        ///    &quot;Type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Genki {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Ladylike&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Ladylike&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Ladylik [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Ladylike {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Majime&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Majime&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Majime&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Majime {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Missy&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Missy&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Missy&quot;,
        ///    &quot;Type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Missy {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Muku&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Muku {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Pride&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pride&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Pride&quot;,
        ///    &quot;Type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Pride {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pure&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Pure {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Rindere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Rindere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Rindere&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Rindere {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Sadist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sadist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Sadist&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Sadist {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Secretary&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Secretary&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Sec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Secretary {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Silent&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Silent&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Silent&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Silent {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Sister&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sister&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Sister&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Sister {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_0020_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0020_T_Yandere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_0021&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;いいお天気ですねー。&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Yandere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02_23485.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_0030_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_0030_T_Yandere&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADV_Yandere {
            get {
                return ResourceManager.GetString("ImmoralVillageADV_Yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi0001&quot;: {
        ///    &quot;ID&quot;: &quot;imvi0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;EmpireClub_Rotary&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_init_chara&quot;
        ///  },
        ///
        ///  &quot;imvi_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_init_hide_men&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: false,
        ///      &quot;ManRequired&quot;: 14,
        ///      &quot;ValidManType&quot;: [
        ///        &quot;Shota&quot;
        ///      ],
        ///      &quot;ModNPC&quot;: [
        ///        {
        ///          &quot;Index&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADVIntroDayTime {
            get {
                return ResourceManager.GetString("ImmoralVillageADVIntroDayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_intro_night_0001&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_night_0001&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_intro_night_0001a&quot;,
        ///    &quot;CameraData&quot;: {
        ///      &quot;FixedPointData&quot;: {
        ///        &quot;PosString&quot;: &quot;999,999,999&quot;,
        ///        &quot;TargetPosString&quot;: &quot;1000,1000,1000&quot;,
        ///        &quot;AroundAngleString&quot;: &quot;0,0&quot;,
        ///        &quot;Distance&quot;: 0
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_intro_night_0001a&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_intro_night_0001a&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADVIntroNightTime {
            get {
                return ResourceManager.GetString("ImmoralVillageADVIntroNightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_phase1_0001&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_phase1_0001&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_phase1_0001a&quot;,
        ///    &quot;CameraData&quot;: {
        ///      &quot;FixedPointData&quot;: {
        ///        &quot;PosString&quot;: &quot;14.20, 1.84, -1.75&quot;,
        ///        &quot;TargetPosString&quot;: &quot;14.09, 1.58, -3.01&quot;,
        ///        &quot;AroundAngleString&quot;: &quot;185.09, 11.53&quot;,
        ///        &quot;Distance&quot;: 1.3
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;imvi_phase1_0001a&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_phase1_0001a&quot;,
        ///    &quot;Type&quot;: &quot;DismissGroup&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;Tag&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADVPhase1 {
            get {
                return ResourceManager.GetString("ImmoralVillageADVPhase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_phase2_init&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_phase2_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_phase2_init_a&quot;
        ///  },
        ///
        ///  &quot;imvi_phase2_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_phase2_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_phase2_init_b&quot;
        ///  },
        ///
        ///  &quot;imvi_phase2_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_phase2_init_b&quot;,
        ///    &quot;Type&quot;: &quot;DismissGroup&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;Tag&quot;: &quot;ALL&quot;,
        ///    &quot;NextStepID&quot;: &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADVPhase2 {
            get {
                return ResourceManager.GetString("ImmoralVillageADVPhase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;imvi_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_postyotogi_init_a&quot;
        ///  },
        ///
        ///  &quot;imvi_postyotogi_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;imvi_postyotogi_init_b&quot;
        ///  },
        ///
        ///  &quot;imvi_postyotogi_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;imvi_postyotogi_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImmoralVillageADVPostYotogi {
            get {
                return ResourceManager.GetString("ImmoralVillageADVPostYotogi", resourceCulture);
            }
        }
    }
}
