//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioLilyBloomingParadise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioLilyBloomingParadise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioLilyBloomingParadise", typeof(ScenarioLilyBloomingParadise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Anesan&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Anesan&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Anesan {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Childhood&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Childhood&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Childhood {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cool&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0020 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Cool {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Curtness&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Curtness&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Curtness {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Dame&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0020 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Dame {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Devilish&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Devilish&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Devilish {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Friendly&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Friendly&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Friendly {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Genki&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Genki&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Genki {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Ladylike&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Ladylike&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Ladylike {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Majime&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Majime&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Majime {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Missy&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Missy&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Missy {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Muku&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0020 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Muku {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Pride&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pride&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Pride {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pure&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hotel_0020 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Pure {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Rindere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Rindere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Rindere {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Sadist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sadist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Sadist {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Secretary&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Secretary&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Secretary {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Silent&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Silent&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Silent {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Sister&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sister&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_hote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Sister {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_intro_0030_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_intro_0030_T_Yandere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_intro_0031&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;……はぁ、はぁ……もっといっぱい触ってほしいです……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Yandere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24725.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: true,
        ///          &quot;StartTime&quot;: 9,
        ///          &quot;Volume&quot;: 0.1
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;lbp_h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADV_Yandere {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADV_Yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp0001&quot;: {
        ///    &quot;ID&quot;: &quot;lbp0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;ShinShitsumu&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_init_chara&quot;
        ///  },
        ///
        ///  &quot;lbp_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_init_hide_pairedmen&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;ManRequired&quot;: 0,
        ///      &quot;RequiresMaidPairMan&quot;: true,
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: true,
        ///      &quot;NPC&quot;: [
        ///        {
        ///          &quot;Index&quot;: 0,
        ///          &quot;Preset&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADVIntro {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_bedroom_0001&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_bedroom_0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;Shukuhakubeya_BedRoom_Night&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_bedroom_0001a&quot;
        ///  },
        ///
        ///  &quot;lbp_bedroom_0001a&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_bedroom_0001a&quot;,
        ///    &quot;Type&quot;: &quot;MakeGroup&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_bedroom_0001b&quot;,
        ///    &quot;GroupFormat&quot;: [
        ///      {
        ///        &quot;GroupIndex&quot;: 0,
        ///        &quot;Maid1&quot;: {
        ///          &quot;Type&quot;: &quot;Maid&quot;,
        ///          &quot;ArrayPosition&quot;: 1
        ///        },
        ///        &quot;Maid2&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADVPhase1Bedroom {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADVPhase1Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;lbp_hotel_0001&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_hotel_0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;Shukuhakubeya_Living&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_hotel_0001a&quot;
        ///  },
        ///
        ///  &quot;lbp_hotel_0001a&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_hotel_0001a&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_hotel_0001b&quot;,
        ///    &quot;CameraData&quot;: {
        ///      &quot;FixedPointData&quot;: {
        ///        &quot;PosString&quot;: &quot;999,999,999&quot;,
        ///        &quot;TargetPosString&quot;: &quot;1000,1000,1000&quot;,
        ///        &quot;AroundAngleString&quot;: &quot;0,0&quot;,
        ///        &quot;Distance&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADVPhase1Hotel {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADVPhase1Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;lbp_phase2_init&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_phase2_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_phase2_init_a&quot;
        ///  },
        ///
        ///  &quot;lbp_phase2_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_phase2_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_phase2_init_b&quot;
        ///  },
        ///
        ///  &quot;lbp_phase2_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_phase2_init_b&quot;,
        ///    &quot;Type&quot;: &quot;Camera&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;lbp_phase2_init_c&quot;,
        ///    &quot;Camera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADVPhase2 {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADVPhase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;lbp_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;lbp_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;hgbc_postyotogi_remove_owner&quot;
        ///  },
        ///
        ///  &quot;hgbc_postyotogi_remove_owner&quot;: {
        ///    &quot;ID&quot;: &quot;hgbc_postyotogi_remove_owner&quot;,
        ///    &quot;Type&quot;: &quot;ListUpdate&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;WaitFullLoad&quot;: true,
        ///    &quot;NextStepID&quot;: &quot;lbp_postyotogi_init_a&quot;,
        ///    &quot;ListUpdateData&quot;: {
        ///      &quot;Remove&quot;: [
        ///        {
        ///          &quot;Type&quot;: &quot;Owner&quot;,
        ///          &quot;SrcPosition&quot;: 0
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LilyBloomingParadiseADVPostYotogi {
            get {
                return ResourceManager.GetString("LilyBloomingParadiseADVPostYotogi", resourceCulture);
            }
        }
    }
}
