//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioPleasureAddictedMaidsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioPleasureAddictedMaidsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioPleasureAddictedMaidsResource", typeof(ScenarioPleasureAddictedMaidsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Anesan&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Anesan&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Anesan {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Childhood&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Childhood&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Childhood {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cool&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Cool {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Cunning&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Cunning&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cunning&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Cunning {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Cunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Curtness&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Curtness&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Curtness {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Dame&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Dame {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Devilish&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Devilish&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Devilish {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Friendly&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Friendly&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Friendly {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Genki&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Genki&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Genki {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Gyaru&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Gyaru&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Gyaru&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Gyaru {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Gyaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Ladylike&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Ladylike&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Ladylike {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Majime&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Majime&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Majime {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Masochist&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Masochist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Masochist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Masochist {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Missy&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Missy&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Missy {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Muku&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Muku {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Pride&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pride&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Pride {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pure&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Pure {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Rindere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Rindere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Rindere {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Sadist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sadist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Sadist {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Secretary&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Secretary&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Secretary {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Silent&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Silent&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Silent {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Sister&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sister&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Sister {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi_0010_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_0010_T_Yandere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_0011&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;んほぉっ、ちんぽ、最高過ぎますっ……！　おっほぉっ、あたしが欲しかったのはこれですっ！　このチンポでずっとこうやって激しくして貰いたかったんですぅっ♪&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Yandere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_BL_64297.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADV_Yandere {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADV_Yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam0001&quot;: {
        ///    &quot;ID&quot;: &quot;pam0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam0001_init_chara&quot;
        ///  },
        ///
        ///  &quot;pam0001_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;pam0001_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam0001_post_init_effect&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: false,
        ///      &quot;ManRequired&quot;: 35,
        ///      &quot;ValidManType&quot;: [
        ///        {
        ///          &quot;Type&quot;: [
        ///            &quot;YoungMan&quot;,
        ///            &quot;MiddleAge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADVIntro {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;pam_post_yotogi&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_init_a&quot;
        ///  },
        ///
        ///  &quot;pam_post_yotogi_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;pam_post_yotogi_init_b&quot;
        ///  },
        ///
        ///  &quot;pam_post_yotogi_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;pam_post_yotogi_init_b&quot;,
        ///    &quot;Type&quot;: &quot;DismissGroup&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;Tag&quot;: &quot;ALL&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PleasureAddictedMaidsADVPostYotogi {
            get {
                return ResourceManager.GetString("PleasureAddictedMaidsADVPostYotogi", resourceCulture);
            }
        }
    }
}
