//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioManInLilies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioManInLilies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.ScenarioManInLilies", typeof(ScenarioManInLilies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Anesan&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Anesan&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Anesan&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Anesan {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Childhood&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Childhood&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Childhood&quot;: {
        ///    &quot;ID&quot;: &quot;mil_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Childhood {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Cool&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cool&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Cool&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Cool&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Cool {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Cunning&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Cunning&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Cunning&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Cunning&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Cunning {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Cunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Curtness&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Curtness&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Curtness&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Curtness {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Dame&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Dame&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Dame&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Dame&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Dame {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Devilish&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Devilish&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Devilish&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Devilish {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Friendly&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Friendly&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Friendly&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Friendly {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Genki&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Genki&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Genki&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Gen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Genki {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Gyaru&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Gyaru&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Gyaru&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Gyaru&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Gya [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Gyaru {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Gyaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Ladylike&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Ladylike&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Ladylike&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Ladylike {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Majime&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Majime&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Majime&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Majime {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Masochist&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Masochist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Masochist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Masochist&quot;: {
        ///    &quot;ID&quot;: &quot;mil_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Masochist {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Missy&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Missy&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Missy&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Mis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Missy {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Muku&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Muku&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Muku&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Muku&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Muku {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Pride&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pride&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Pride&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Pride {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Pure&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Pure&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Pure&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T_Pure&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Pure {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Rindere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Rindere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Rindere&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Rindere {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Sadist&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sadist&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Sadist&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Sadist {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Secretary&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Secretary&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Secretary&quot;: {
        ///    &quot;ID&quot;: &quot;mil_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Secretary {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Silent&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Silent&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Silent&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Silent {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Sister&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Sister&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Sister&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0030_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Sister {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil_intro_0020_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_0020_T_Yandere&quot;,
        ///    &quot;Type&quot;: &quot;Talk&quot;,
        ///    &quot;WaitingType&quot;: &quot;Click&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_intro_0021_Branch&quot;,
        ///    &quot;TalkData&quot;: {
        ///      &quot;SpecificSpeaker&quot;: &quot;Maid&quot;,
        ///      &quot;UseBranchIndex&quot;: true,
        ///      &quot;Text&quot;: &quot;もう、ご主人様、ホントに変態なんですからぁ……&quot;,
        ///      &quot;VoiceData&quot;: {
        ///        &quot;Yandere&quot;: {
        ///          &quot;VoiceFile&quot;: &quot;H0_GP02C_24616.ogg&quot;,
        ///          &quot;IsChoppingAudio&quot;: false
        ///        }
        ///      }
        ///    }
        ///  },
        ///
        ///  &quot;mil_intro_0030_T_Yandere&quot;: {
        ///    &quot;ID&quot;: &quot;mil_intro_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADV_Yandere {
            get {
                return ResourceManager.GetString("ManInLiliesADV_Yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;mil0001&quot;: {
        ///    &quot;ID&quot;: &quot;mil0001&quot;,
        ///    &quot;Type&quot;: &quot;BG&quot;,
        ///    &quot;Tag&quot;: &quot;&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_init_chara&quot;
        ///  },
        ///
        ///  &quot;mil_init_chara&quot;: {
        ///    &quot;ID&quot;: &quot;mil_init_chara&quot;,
        ///    &quot;Type&quot;: &quot;CharaInit&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_init_hide_pairedmen&quot;,
        ///    &quot;CharaInitData&quot;: {
        ///      &quot;ManRequired&quot;: 0,
        ///      &quot;RequiresMaidPairMan&quot;: true,
        ///      &quot;IsClubOwnerADVMainCharacter&quot;: true
        ///    }
        ///  },
        ///
        ///  &quot;mil_init_hide_pairedmen&quot;: {
        ///    &quot;ID&quot;: &quot;mil_init_hide_pairedmen&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADVIntro {
            get {
                return ResourceManager.GetString("ManInLiliesADVIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;mil_postyotogi_init&quot;: {
        ///    &quot;ID&quot;: &quot;mil_postyotogi_init&quot;,
        ///    &quot;Type&quot;: &quot;CloseMsgPanel&quot;,
        ///    &quot;WaitingType&quot;: &quot;SystemFadeOut&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_postyotogi_init_a&quot;
        ///  },
        ///
        ///  &quot;mil_postyotogi_init_a&quot;: {
        ///    &quot;ID&quot;: &quot;mil_postyotogi_init_a&quot;,
        ///    &quot;Type&quot;: &quot;BGM&quot;,
        ///    &quot;Tag&quot;: &quot;BGM011.ogg&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;NextStepID&quot;: &quot;mil_postyotogi_init_b&quot;
        ///  },
        ///
        ///  &quot;mil_postyotogi_init_b&quot;: {
        ///    &quot;ID&quot;: &quot;mil_postyotogi_init_b&quot;,
        ///    &quot;Type&quot;: &quot;DismissGroup&quot;,
        ///    &quot;WaitingType&quot;: &quot;Auto&quot;,
        ///    &quot;Tag&quot;: &quot;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManInLiliesADVPostYotogi {
            get {
                return ResourceManager.GetString("ManInLiliesADVPostYotogi", resourceCulture);
            }
        }
    }
}
