//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;ChangePosition&quot;: {
        ///    &quot;Name&quot;: &quot;体位変更&quot;,
        ///    &quot;Type&quot;: &quot;Common&quot;
        ///  },
        ///  &quot;ChangePositionAll&quot;: {
        ///    &quot;Name&quot;: &quot;一緒に体位変更&quot;,
        ///    &quot;Type&quot;: &quot;Common&quot;
        ///  },
        ///  &quot;ChangeFormation&quot;: {
        ///    &quot;Name&quot;: &quot;一緒に位置変更&quot;,
        ///    &quot;Type&quot;: &quot;Common&quot;
        ///  },
        ///  &quot;ChangePartner&quot;: {
        ///    &quot;Name&quot;: &quot;パートナー交換&quot;,
        ///    &quot;Type&quot;: &quot;Common&quot;
        ///  },
        ///  &quot;FetishOrgy&quot;: {
        ///    &quot;Name&quot;: &quot;性癖「乱交大好き」&quot;,
        ///    &quot;Type&quot;: &quot;Fetish&quot;,
        ///    &quot;FetishID&quot;: 99001,
        ///    &quot;ConditionCheckTexts&quot;: [
        ///      {
        ///        &quot;Field&quot;: &quot;ManCount&quot;,
        ///        &quot;DisplayText&quot;: &quot;[=ManCount]人以上とセックスする&quot;
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ExtraYotogiComands {
            get {
                return ResourceManager.GetString("ExtraYotogiComands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;Houshi&quot;: {
        ///    &quot;DisplayName&quot;: &quot;一緒に奉仕する&quot;,
        ///    &quot;IsRandom&quot;: false,
        ///    &quot;CoordinateList&quot;: [
        ///      {
        ///        &quot;MaxGroup&quot;: 4,
        ///        &quot;GroupCoordinates&quot;: [
        ///          {
        ///            &quot;ArrayPosition&quot;: 0,
        ///            &quot;PosString&quot;: &quot;8.45, 0.5, -1.5&quot;,
        ///            &quot;RotString&quot;: &quot;0.0, 0.0, 0.0, 1.0&quot;,
        ///            &quot;IKAttach&quot;: [
        ///              {
        ///                &quot;PosString&quot;: &quot;0.02, -0.04, -0.1&quot;,
        ///                &quot;AttachType&quot;: &quot;NewPoint&quot;,
        ///                &quot;Source&quot;: {
        ///                  &quot;ArrayIndex&quot;: 0,
        ///         [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string HaremKingYotogiMapCoordinates {
            get {
                return ResourceManager.GetString("HaremKingYotogiMapCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 イベント「[=EventName]」には最低[=Min]名、最大[=Max]名が必要です。 的當地語系化字串。
        /// </summary>
        internal static string MaidCountRequirementWarning {
            get {
                return ResourceManager.GetString("MaidCountRequirementWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type,FileName
        ///head,mhead003_i_.menu
        ///head,mhead000_i_.menu
        ///head,mhead004_i_.menu
        ///head,mhead002_i_.menu
        ///head,mhead001_i_.menu
        ///head,mhead008_i_.menu
        ///head,mhead005_i_.menu
        ///head,mhead006_i_.menu
        ///head,mhead007_i_.menu
        ///head,mhead009_i_.menu
        ///head,mhead010_i_.menu
        ///body,mbody004_i_.menu
        ///body,mbody_i_.menu
        ///body,mbody001_i_.menu
        ///body,mbody003_i_.menu
        ///body,mbody006_i_.menu
        ///body,mbody005_i_.menu
        ///body,mbody002_i_.menu
        /// 的當地語系化字串。
        /// </summary>
        internal static string ManBodyOptions {
            get {
                return ResourceManager.GetString("ManBodyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type,Tag,FileName,MotionFileName,Label,VoiceType,dummy
        ///ManKneeDown,ran3p_udemoti_kouhaii_fera_gr_m2.anm,ran3p_udemoti_kouhaii_fera_gr_m2.anm,,,,
        ///MaidOnFloor,om_onani_1_f.anm,om_onani_1_f.anm,sex_OM_onani.ks,*激しさ１,Piston,
        /// 的當地語系化字串。
        /// </summary>
        internal static string MasturbationMotion {
            get {
                return ResourceManager.GetString("MasturbationMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [
        ///  {
        ///    &quot;ID&quot;: 99001,
        ///    &quot;DrawName&quot;: &quot;乱交大好き&quot;,
        ///    &quot;UniqueName&quot;: &quot;乱交大好き&quot;,
        ///    &quot;ColorType&quot;: &quot;Red&quot;,
        ///    &quot;Conditions&quot;: 
        ///    {
        ///      &quot;ManCount&quot;: 3,
        ///      &quot;OrgasmCount&quot;: 10
        ///    }
        ///  }
        ///]
        /// 的當地語系化字串。
        /// </summary>
        internal static string ModFetish {
            get {
                return ResourceManager.GetString("ModFetish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [
        ///  {
        ///    &quot;ScenarioID&quot;: 9900001,
        ///    &quot;CategoryID&quot;: 99000,
        ///    &quot;ADVEntryStep&quot;: &quot;org0001&quot;,
        ///    &quot;YotogiTypeEnumString&quot;: &quot;NewSex&quot;,
        ///    &quot;CondSalonGrade&quot;: 0,
        ///    &quot;DisplayName&quot;: &quot;エンパイアクラブ大姦射祭&quot;,
        ///    &quot;Information&quot;: &quot;恋人の本当の姿が知りたい、もっと愛する人の淫乱な顔が見たい。そんな複雑な気持ちを抱えた中で、ご主人様はとあるイベントを開催する…&quot;,
        ///    &quot;Icon&quot;: &quot;mod_icon_orgy_party&quot;,
        ///    &quot;IsNetorare&quot;: true,
        ///    &quot;IsCommu&quot;: false,
        ///    &quot;ModeEnumString&quot;: &quot;COM3D&quot;,
        ///    &quot;TypeEnumString&quot;: &quot;Yotogi&quot;,
        ///    &quot;ContractEnumString&quot;: [ &quot;Exclusive&quot;, &quot;Free&quot; ],
        ///    &quot;SexExperienceEnumString [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ModScenario {
            get {
                return ResourceManager.GetString("ModScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [
        ///  {
        ///    &quot;CategoryID&quot;: 99000,
        ///    &quot;DisplayName&quot;: &quot;NTR・パーティー\n(Mod)&quot;
        ///  },
        ///  {
        ///    &quot;CategoryID&quot;: 99010,
        ///    &quot;DisplayName&quot;: &quot;ハーレム・パーティー\n(Mod)&quot;
        ///  }
        ///]
        /// 的當地語系化字串。
        /// </summary>
        internal static string ModScenarioCategory {
            get {
                return ResourceManager.GetString("ModScenarioCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;Theatre_Scattered&quot;: {
        ///    &quot;MapID&quot;: 10,
        ///    &quot;DisplayName&quot;: &quot;バラバラ&quot;,
        ///    &quot;IsRandom&quot;: true,
        ///    &quot;CoordinateList&quot;: [
        ///      {
        ///        &quot;MaxGroup&quot;: 20,
        ///        &quot;GroupCoordinates&quot;: [
        ///          {
        ///            &quot;ArrayPosition&quot;: 0,
        ///            &quot;PosString&quot;: &quot;0.0, 0.0, -1.4&quot;,
        ///            &quot;RotString&quot;: &quot;0.0, -0.4, 0.0, 0.9&quot;
        ///          },
        ///          {
        ///            &quot;ArrayPosition&quot;: 1,
        ///            &quot;PosString&quot;: &quot;-1.5, 0.0, -3.5&quot;,
        ///            &quot;RotString&quot;: &quot;0.0, 0.2, 0.0, 1.0&quot;
        ///          },
        ///          {
        ///        [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string OrgyYotogiMapCoordinates {
            get {
                return ResourceManager.GetString("OrgyYotogiMapCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;Houshi&quot;: {
        ///    &quot;DefaultSexPosID&quot;: 5,
        ///    &quot;IsRandomAssign&quot;: false,
        ///    &quot;IsShuffleMaidList&quot;: true,
        ///    &quot;IsShuffleManList&quot;: false,
        ///    &quot;ExcludePersonality&quot;: [ 190, 200, 230 ],
        ///    &quot;GroupSetup&quot;: [
        ///      {
        ///        &quot;ArrayPosition&quot;: 0,
        ///        &quot;ManCount&quot;: 1,
        ///        &quot;MaidCount&quot;: 2,
        ///        &quot;IsAutomatedGroup&quot;: false
        ///      },
        ///      {
        ///        &quot;ArrayPosition&quot;: 1,
        ///        &quot;ManCount&quot;: 1,
        ///        &quot;MaidCount&quot;: 1,
        ///        &quot;IsAutomatedGroup&quot;: false
        ///      },
        ///      {
        ///        &quot;ArrayPosition&quot;: 2,
        ///     [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string PartyGroupSetup_HaremKing {
            get {
                return ResourceManager.GetString("PartyGroupSetup_HaremKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;Theatre_Scattered&quot;: {
        ///    &quot;IsRandomAssign&quot;: true,
        ///    &quot;IsShuffleMaidList&quot;: true,
        ///    &quot;IsShuffleManList&quot;: true
        ///  },
        ///  &quot;Theatre_2RowsA&quot;: {
        ///    &quot;IsRandomAssign&quot;: true,
        ///    &quot;IsShuffleMaidList&quot;: true,
        ///    &quot;IsShuffleManList&quot;: true
        ///  },
        ///  &quot;Theatre_2RowsB&quot;: {
        ///    &quot;IsRandomAssign&quot;: true,
        ///    &quot;IsShuffleMaidList&quot;: true,
        ///    &quot;IsShuffleManList&quot;: true
        ///  },
        ///  &quot;Theatre_CircleA&quot;: {
        ///    &quot;IsRandomAssign&quot;: true,
        ///    &quot;IsShuffleMaidList&quot;: true,
        ///    &quot;IsShuffleManList&quot;: true
        ///  },
        ///  &quot;Theatre_CircleB&quot;: {
        ///  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string PartyGroupSetup_OrgyParty {
            get {
                return ResourceManager.GetString("PartyGroupSetup_OrgyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;Vagina&quot;: {
        ///    &quot;Slotname&quot;: &quot;body&quot;,
        ///    &quot;Part&quot;: &quot;Hibu&quot;,
        ///    &quot;MatNo&quot;: 0,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 18,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Seieki/spe001:Seieki/spe002:Seieki/spe009:Seieki/spe014&quot;,
        ///      &quot;Seieki/spe001r:Seieki/spe002r:Seieki/spe009r:Seieki/spe014r&quot;,
        ///      &quot;Seieki/spe001:Seieki/spe001r:Seieki/spe002:Seieki/spe002r:Seieki/spe009:Seieki/spe009r:Seieki/spe014:Seieki/spe014r&quot;
        ///    ],
        ///    &quot;BlendMode&quot;: &quot;Alpha&quot;,
        ///    &quot;Add&quot;: true,
        ///    &quot;XRan [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SemenPattern {
            get {
                return ResourceManager.GetString("SemenPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VoiceType,ExcitementLevel,NormalFace,EstrusFace,NormalBlend,EstrusBlend,dummy
        ///Piston,0,目口閉じ;エロ我慢１;エロ期待;エロ痛み２;エロ興奮２,エロメソ泣き;エロ痛み２;むー,頬０涙０,頬３涙０,
        ///Piston,1,エロ羞恥２;エロ羞恥１;エロ我慢２,エロ期待;エロ怯え;エロ興奮２,頬１涙０,頬３涙０,
        ///Piston,2,エロ羞恥２;エロ興奮３;発情,エロ怯え;エロ我慢１;エロ興奮３;エロ羞恥２,頬２涙０,頬３涙０,
        ///Piston,3,エロ興奮３;エロ羞恥３;エロメソ泣き,エロ羞恥３;エロ興奮３;エロ我慢２;エロメソ泣き,頬３涙０,頬３涙０,
        ///PistonExcite,0,目口閉じ;エロ羞恥１;エロ痛み２,エロメソ泣き;エロ痛み２;むー,頬０涙０,頬３涙０,
        ///PistonExcite,1,エロ怯え;拗ね;エロ我慢２,エロ怯え;エロ期待,頬１涙０,頬３涙０,
        ///PistonExcite,2,エロ我慢２;エロ羞恥２;エロ興奮３,エロ怯え;エロ興奮３;エロ我慢１;エロ羞恥２,頬２涙０,頬３涙０,
        ///PistonExci [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosFace {
            get {
                return ResourceManager.GetString("SexPosFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SexPosID,DisplayName,MotionFile,GroupType,IsActive,Order,P10,P20,P30,P40,P50,P60,P70,P80,P90,P100,P110,P120,P130,P140,P150,P160,P170,P180,P190,P200,P210,P220,P230,IsDialogueAllowed,IsChoosable,dummy
        ///1,並べ正常位,sex_OM_seijyoui.ks,MF,TRUE,50,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,18910,20210,90,90,85110,TRUE,TRUE,
        ///2,並べ正常位（アナル）,sex_OM_seijyouiA.ks,MF,TRUE,51,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,18920,20220,110,110,110,TRUE,TRUE,
        ///3,尻並べ,sex_OM_kouhaii.ks,MF,TRUE, [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosList_HaremKing {
            get {
                return ResourceManager.GetString("SexPosList_HaremKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SexPosID,DisplayName,MotionFile,GroupType,IsActive,Order,P10,P20,P30,P40,P50,P60,P70,P80,P90,P100,P110,P120,P130,P140,P150,P160,P170,P180,P190,P200,P210,P220,P230,IsDialogueAllowed,IsChoosable,dummy
        ///1,愛撫,sex_OM_aibu.ks,MF,TRUE,1,53000,53000,53000,53000,53000,53000,53000,38000,38000,38000,38000,38000,38000,53000,53000,38000,53000,53000,69000,69000,53000,53000,99000,TRUE,TRUE,
        ///2,セックス正常位,sex_OM_seijyoui.ks,MF,TRUE,50,53030,53030,53030,53030,53030,53030,53030,38030,38030,38030,38030,38030,38030,53030,53030,38 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosList_OrgyParty {
            get {
                return ResourceManager.GetString("SexPosList_OrgyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type,ExcitementLevel,
        ///Piston,0,SE027.ogg
        ///Piston,1,SE027.ogg
        ///Piston,2,SE028.ogg
        ///Piston,3,SE029.ogg
        ///Fellatio,0,SE030.ogg
        ///Fellatio,1,SE030.ogg
        ///Fellatio,2,SE031.ogg
        ///Fellatio,3,SE032.ogg
        /// 的當地語系化字串。
        /// </summary>
        internal static string SexPosSE {
            get {
                return ResourceManager.GetString("SexPosSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SexPosID,Label,Type,SemenPattern1,SemenPattern2,SemenTarget1,SemenTarget2,VoiceLabel1,VoiceLabel2,WaitLabel1,WaitLabel2,dummy
        ///1,*待機,Waiting,,,,,Waiting,,,,
        ///1,*初々しい秘部弄り絶頂,Orgasm,None,,,,Aibu,,OrgasmWait,,
        ///2,*挿入,Insert,,,,,Insert,,,,
        ///2,*待機,Waiting,,,,,Waiting,,,,
        ///2,*初々しい射精外,Orgasm,Belly,,Maid1,,Piston,,OrgasmWait,,
        ///2,*初々しい射精中,Orgasm,Vagina,,Maid1,,Piston,,OrgasmWait,,
        ///3,*挿入,Insert,,,,,Insert,,,,
        ///3,*待機,Waiting,,,,,Waiting,,,,
        ///3,*初々しい射精外,Orgasm,Belly,,Maid1,,Piston,,OrgasmWait,,
        ///3,*初々しい射精中,Orgasm,Vagi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosSpecialLabels {
            get {
                return ResourceManager.GetString("SexPosSpecialLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SexPosID,ExcitementLevel,LabelName,VoiceType,VoiceType2,LabelGroupID
        ///100,0,*待機,NoVoiceSmile,,1
        ///100,1,*待機,NoVoiceSmile,,1
        ///100,2,*待機,NoVoiceSmile,,1
        ///100,3,*待機,NoVoiceSmile,,1
        ///101,0,*待機,Waiting,,2
        ///101,1,*待機,Waiting,,2
        ///101,2,*待機,Waiting,,2
        ///101,3,*待機,Waiting,,2
        ///102,0,*激しさ１乳首舐め,LickJob,,3
        ///102,1,*激しさ１乳首舐め,LickJob,,3
        ///102,2,*激しさ２乳首舐め,LickJob,,3
        ///102,3,*激しさ３乳首舐め,LickJob,,3
        ///103,0,*待機,Waiting,,4
        ///103,1,*待機,Waiting,,4
        ///103,2,*待機,Waiting,,4
        ///103,3,*待機,Waiting,,4
        ///104,0,*靴舐め,LickJob,,5
        ///104,1,*靴舐め,LickJob,,5
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosValidLabels_HaremKing {
            get {
                return ResourceManager.GetString("SexPosValidLabels_HaremKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SexPosID,ExcitementLevel,LabelName,VoiceType,VoiceType2,LabelGroupID,,,,
        ///1,0,*激しさ１秘部弄り,Piston,,1,,,,
        ///1,1,*激しさ１秘部弄り,Piston,,1,,,,
        ///1,2,*激しさ２秘部弄り,Piston,,1,,,,
        ///1,3,*激しさ３秘部弄り,Piston,,1,,,,
        ///2,0,*激しさ１,Piston,,2,,,,
        ///2,1,*激しさ１,Piston,,2,,,,
        ///2,2,*激しさ２,Piston,,2,,,,
        ///2,3,*激しさ３,Piston,,2,,,,
        ///2,0,*激しさ１キス,Kiss,,3,,,,
        ///2,1,*激しさ１キス,Kiss,,3,,,,
        ///2,2,*激しさ２キス,Kiss,,3,,,,
        ///2,3,*激しさ３キス,Kiss,,3,,,,
        ///2,0,*激しさ１胸揉み,Piston,,4,,,,
        ///2,1,*激しさ１胸揉み,Piston,,4,,,,
        ///2,2,*激しさ２胸揉み,Piston,,4,,,,
        ///2,3,*激しさ３胸揉み,Piston,,4,,,,
        ///3,0,*激しさ１, [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SexPosValidLabels_OrgyParty {
            get {
                return ResourceManager.GetString("SexPosValidLabels_OrgyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///  &quot;NormalPlay&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;Orgasm&quot; ]
        ///  },
        ///  &quot;Orgasm&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;OrgasmEnd&quot; ]
        ///  },
        ///  &quot;OrgasmEnd&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;OrgasmWait&quot; ]
        ///  },
        ///  &quot;OrgasmWait&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;ChangePosition&quot;, &quot;ChangePosition&quot;, &quot;ChangePosition&quot;, &quot;ChangePosition&quot;, &quot;Insert&quot; ]
        ///  },
        ///  &quot;ChangePosition&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;Insert&quot; ]
        ///  },
        ///  &quot;Insert&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;InsertEnd&quot; ]
        ///  },
        ///  &quot;InsertEnd&quot;: {
        ///    &quot;NextStates&quot;: [ &quot;NormalPlay&quot; ]
        ///  }
        ///}
        /// 的當地語系化字串。
        /// </summary>
        internal static string SexStateDescription {
            get {
                return ResourceManager.GetString("SexStateDescription", resourceCulture);
            }
        }
    }
}
