//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント「[=EventName]」にはメイド人数は偶数が必要です。.
        /// </summary>
        internal static string MaidCountRequirementEvenNumber {
            get {
                return ResourceManager.GetString("MaidCountRequirementEvenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント「[=EventName]」には最低[=Min]名、最大[=Max]名が必要です。.
        /// </summary>
        internal static string MaidCountRequirementWarning {
            get {
                return ResourceManager.GetString("MaidCountRequirementWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント「[=EventName]」には[=Min]名が必要です。.
        /// </summary>
        internal static string MaidCountRequirementWarningExactCount {
            get {
                return ResourceManager.GetString("MaidCountRequirementWarningExactCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullNude.
        /// </summary>
        internal static string NudeClothesSetID {
            get {
                return ResourceManager.GetString("NudeClothesSetID", resourceCulture);
            }
        }
    }
}
