//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Voice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voice() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.WildParty.Plugin.Resx.Voice", typeof(Voice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Muku,Insert,0,H0_00261.ogg,H0_00281.ogg,
        ///Muku,Insert,1,H0_00262.ogg,H0_00282.ogg,
        ///Muku,Insert,2,H0_00263.ogg,H0_00283.ogg,
        ///Muku,Insert,3,H0_00264.ogg,H0_00284.ogg,
        ///Muku,InsertMouth,0,H0_00285.ogg,H0_00285.ogg,
        ///Muku,InsertMouth,1,H0_00286.ogg,H0_00286.ogg,
        ///Muku,InsertMouth,2,H0_00287.ogg,H0_00287.ogg,
        ///Muku,InsertMouth,3,H0_00288.ogg,H0_00288.ogg,
        ///Majime,Insert,0,H1_00433.ogg,H1_00453.ogg,
        ///Majime,Insert,1,H1_00434.ogg,H1_00454.ogg,
        ///Majime,I [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_All_Insert {
            get {
                return ResourceManager.GetString("Voice_All_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,Type,FileName,choppingTime,dummy
        ///Muku,Aibu,H0_X01_62795.ogg,5,
        ///Muku,Aibu,H0_X01_62796.ogg,5,
        ///Muku,Piston,H0_X01_62797.ogg,5,
        ///Muku,Piston,H0_X01_62798.ogg,5,
        ///Muku,Piston,H0_X01_62801.ogg,5,
        ///Muku,Piston,H0_X01_62802.ogg,5,
        ///Muku,Fellatio,H0_X01_62805.ogg,5,
        ///Muku,Fellatio,H0_X01_62806.ogg,5,
        ///Muku,FellatioFace,H0_X01_62807.ogg,5,
        ///Muku,FellatioFace,H0_X01_62808.ogg,5,
        ///Muku,3PFellatio,H0_X01_61902.ogg,5,
        ///Muku,3PFellatio,H0_X01_61903.ogg,5,
        ///Muku,3PFellatioFace,H0_X01_61904.ogg,5,
        ///Muku,3PFe [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_All_OrgasmScream {
            get {
                return ResourceManager.GetString("Voice_All_OrgasmScream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Muku,OrgasmWait,0,H0_00337_vd.ogg,H0_00352_vd.ogg,
        ///Muku,OrgasmWait,0,H0_adult_61309.ogg,H0_adult_61324.ogg,
        ///Muku,OrgasmWait,1,H0_00337_vd.ogg,H0_00352_vd.ogg,
        ///Muku,OrgasmWait,1,H0_adult_61309.ogg,H0_adult_61324.ogg,
        ///Muku,OrgasmWait,2,H0_00338_vd.ogg,H0_00353_vd.ogg,
        ///Muku,OrgasmWait,2,H0_adult_61310.ogg,H0_adult_61325.ogg,
        ///Muku,OrgasmWait,3,H0_00339_vd.ogg,H0_00354_vd.ogg,
        ///Muku,OrgasmWait,3,H0_adult_61311.ogg,H0_adult_61326.ogg,
        ///Muku,OrgasmW [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_All_OrgasmWait {
            get {
                return ResourceManager.GetString("Voice_All_OrgasmWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Anesan,Piston,0,S4_08127.ogg,S4_102930.ogg,
        ///Anesan,Piston,0,S4_08128.ogg,S4_102931.ogg,
        ///Anesan,Piston,0,S4_adult_54506.ogg,S4_adult_54722.ogg,
        ///Anesan,Piston,0,S4_adult_54507.ogg,S4_adult_54723.ogg,
        ///Anesan,Piston,1,S4_08129.ogg,S4_102932.ogg,
        ///Anesan,Piston,1,S4_08130.ogg,S4_102933.ogg,
        ///Anesan,Piston,1,S4_adult_54508.ogg,S4_adult_54724.ogg,
        ///Anesan,Piston,1,S4_adult_54509.ogg,S4_adult_54725.ogg,
        ///Anesan,Piston,2,S4_08131.ogg,S4_102934.ogg,
        ///Ane [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Anesan {
            get {
                return ResourceManager.GetString("Voice_Anesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Childhood,Piston,0,H10_03841.ogg,H10_04057.ogg,
        ///Childhood,Piston,0,H10_03842.ogg,H10_04058.ogg,
        ///Childhood,Piston,0,H10_adult_55529.ogg,H10_adult_55745.ogg,
        ///Childhood,Piston,0,H10_adult_55530.ogg,H10_adult_55746.ogg,
        ///Childhood,Piston,1,H10_03843.ogg,H10_04059.ogg,
        ///Childhood,Piston,1,H10_03844.ogg,H10_04060.ogg,
        ///Childhood,Piston,1,H10_adult_55531.ogg,H10_adult_55747.ogg,
        ///Childhood,Piston,1,H10_adult_55532.ogg,H10_adult_55748.ogg,
        ///Childhood,Pi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Childhood {
            get {
                return ResourceManager.GetString("Voice_Childhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Cool,Piston,0,S1_02309.ogg,S1_102717.ogg,
        ///Cool,Piston,0,S1_02310.ogg,S1_102718.ogg,
        ///Cool,Piston,0,S1_adult_53503.ogg,S1_adult_53719.ogg,
        ///Cool,Piston,0,S1_adult_53504.ogg,S1_adult_53720.ogg,
        ///Cool,Piston,1,S1_02311.ogg,S1_102719.ogg,
        ///Cool,Piston,1,S1_02312.ogg,S1_102720.ogg,
        ///Cool,Piston,1,S1_adult_53505.ogg,S1_adult_53721.ogg,
        ///Cool,Piston,1,S1_adult_53506.ogg,S1_adult_53722.ogg,
        ///Cool,Piston,2,S1_02313.ogg,S1_102721.ogg,
        ///Cool,Piston,2,S1_0231 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Cool {
            get {
                return ResourceManager.GetString("Voice_Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Cunning,Piston,0,H12_01205.ogg,H12_01205.ogg,
        ///Cunning,Piston,0,H12_01206.ogg,H12_01206.ogg,
        ///Cunning,Piston,0,H12_adult_06460.ogg,H12_adult_06460.ogg,
        ///Cunning,Piston,0,H12_adult_06461.ogg,H12_adult_06461.ogg,
        ///Cunning,Piston,1,H12_01207.ogg,H12_01207.ogg,
        ///Cunning,Piston,1,H12_01208.ogg,H12_01208.ogg,
        ///Cunning,Piston,1,H12_adult_06462.ogg,H12_adult_06462.ogg,
        ///Cunning,Piston,1,H12_adult_06463.ogg,H12_adult_06463.ogg,
        ///Cunning,Piston,2,H12_01209.o [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Cunning {
            get {
                return ResourceManager.GetString("Voice_Cunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Curtness,Piston,0,H8_01131.ogg,H8_01347.ogg,
        ///Curtness,Piston,0,H8_01132.ogg,H8_01348.ogg,
        ///Curtness,Piston,0,H8_adult_56103.ogg,H8_adult_56319.ogg,
        ///Curtness,Piston,0,H8_adult_56104.ogg,H8_adult_56320.ogg,
        ///Curtness,Piston,1,H8_01133.ogg,H8_01349.ogg,
        ///Curtness,Piston,1,H8_01134.ogg,H8_01350.ogg,
        ///Curtness,Piston,1,H8_adult_56105.ogg,H8_adult_56321.ogg,
        ///Curtness,Piston,1,H8_adult_56106.ogg,H8_adult_56322.ogg,
        ///Curtness,Piston,2,H8_01135.ogg,H8_01 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Curtness {
            get {
                return ResourceManager.GetString("Voice_Curtness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Dame,Piston,0,V0_00480.ogg,V0_00696.ogg,
        ///Dame,Piston,0,V0_00481.ogg,V0_00697.ogg,
        ///Dame,Piston,0,V0_adult_15033.ogg,V0_adult_15249.ogg,
        ///Dame,Piston,0,V0_adult_15034.ogg,V0_adult_15250.ogg,
        ///Dame,Piston,1,V0_00482.ogg,V0_00698.ogg,
        ///Dame,Piston,1,V0_00483.ogg,V0_00699.ogg,
        ///Dame,Piston,1,V0_adult_15035.ogg,V0_adult_15251.ogg,
        ///Dame,Piston,1,V0_adult_15036.ogg,V0_adult_15252.ogg,
        ///Dame,Piston,2,V0_00484.ogg,V0_00700.ogg,
        ///Dame,Piston,2,V0_00485.ogg [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Dame {
            get {
                return ResourceManager.GetString("Voice_Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Devilish,Piston,0,H4_00853.ogg,H4_01069.ogg,
        ///Devilish,Piston,0,H4_00854.ogg,H4_01070.ogg,
        ///Devilish,Piston,0,H4_adult_57256.ogg,H4_adult_57472.ogg,
        ///Devilish,Piston,0,H4_adult_57257.ogg,H4_adult_57473.ogg,
        ///Devilish,Piston,1,H4_00855.ogg,H4_01071.ogg,
        ///Devilish,Piston,1,H4_00856.ogg,H4_01072.ogg,
        ///Devilish,Piston,1,H4_adult_57258.ogg,H4_adult_57474.ogg,
        ///Devilish,Piston,1,H4_adult_57259.ogg,H4_adult_57475.ogg,
        ///Devilish,Piston,2,H4_00857.ogg,H4_01 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Devilish {
            get {
                return ResourceManager.GetString("Voice_Devilish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Friendly,Piston,0,V1_00482.ogg,V1_00698.ogg,
        ///Friendly,Piston,0,V1_00483.ogg,V1_00699.ogg,
        ///Friendly,Piston,0,V1_adult_16048.ogg,V1_adult_16264.ogg,
        ///Friendly,Piston,0,V1_adult_16049.ogg,V1_adult_16265.ogg,
        ///Friendly,Piston,1,V1_00484.ogg,V1_00700.ogg,
        ///Friendly,Piston,1,V1_00485.ogg,V1_00701.ogg,
        ///Friendly,Piston,1,V1_adult_16050.ogg,V1_adult_16266.ogg,
        ///Friendly,Piston,1,V1_adult_16051.ogg,V1_adult_16267.ogg,
        ///Friendly,Piston,2,V1_00486.ogg,V1_00 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Friendly {
            get {
                return ResourceManager.GetString("Voice_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Genki,Piston,0,S5_04047.ogg,S5_102337.ogg,
        ///Genki,Piston,0,S5_04048.ogg,S5_102338.ogg,
        ///Genki,Piston,0,S5_adult_53628.ogg,S5_adult_53844.ogg,
        ///Genki,Piston,0,S5_adult_53629.ogg,S5_adult_53845.ogg,
        ///Genki,Piston,1,S5_04049.ogg,S5_102339.ogg,
        ///Genki,Piston,1,S5_04050.ogg,S5_102340.ogg,
        ///Genki,Piston,1,S5_adult_53630.ogg,S5_adult_53846.ogg,
        ///Genki,Piston,1,S5_adult_53631.ogg,S5_adult_53847.ogg,
        ///Genki,Piston,2,S5_04051.ogg,S5_102341.ogg,
        ///Genki,Piston [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Genki {
            get {
                return ResourceManager.GetString("Voice_Genki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Gyaru,Piston,0,H13_01036.ogg,H13_01252.ogg,
        ///Gyaru,Piston,0,H13_01037.ogg,H13_01253.ogg,
        ///Gyaru,Piston,0,H13_galsp_06721.ogg,H13_galsp_06937.ogg,
        ///Gyaru,Piston,0,H13_galsp_06722.ogg,H13_galsp_06938.ogg,
        ///Gyaru,Piston,1,H13_01038.ogg,H13_01254.ogg,
        ///Gyaru,Piston,1,H13_01039.ogg,H13_01255.ogg,
        ///Gyaru,Piston,1,H13_galsp_06723.ogg,H13_galsp_06939.ogg,
        ///Gyaru,Piston,1,H13_galsp_06724.ogg,H13_galsp_06940.ogg,
        ///Gyaru,Piston,2,H13_01040.ogg,H13_01256.ogg,        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Gyaru {
            get {
                return ResourceManager.GetString("Voice_Gyaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Ladylike,Piston,0,H5_00592.ogg,H5_00808.ogg,
        ///Ladylike,Piston,0,H5_00593.ogg,H5_00809.ogg,
        ///Ladylike,Piston,0,H5_adult_55527.ogg,H5_adult_55743.ogg,
        ///Ladylike,Piston,0,H5_adult_55528.ogg,H5_adult_55744.ogg,
        ///Ladylike,Piston,1,H5_00594.ogg,H5_00810.ogg,
        ///Ladylike,Piston,1,H5_00595.ogg,H5_00811.ogg,
        ///Ladylike,Piston,1,H5_adult_55529.ogg,H5_adult_55745.ogg,
        ///Ladylike,Piston,1,H5_adult_55530.ogg,H5_adult_55746.ogg,
        ///Ladylike,Piston,2,H5_00596.ogg,H5_00 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Ladylike {
            get {
                return ResourceManager.GetString("Voice_Ladylike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Majime,Piston,0,H1_00225.ogg,H1_00401.ogg,
        ///Majime,Piston,0,H1_00226.ogg,H1_00402.ogg,
        ///Majime,Piston,0,H1_08952.ogg,H1_00401.ogg,
        ///Majime,Piston,0,H1_08953.ogg,H1_00402.ogg,
        ///Majime,Piston,0,H1_adult_60551.ogg,H1_adult_60767.ogg,
        ///Majime,Piston,0,H1_adult_60552.ogg,H1_adult_60768.ogg,
        ///Majime,Piston,1,H1_00227.ogg,H1_00403.ogg,
        ///Majime,Piston,1,H1_00228.ogg,H1_00404.ogg,
        ///Majime,Piston,1,H1_08954.ogg,H1_00403.ogg,
        ///Majime,Piston,1,H1_08955.ogg,H1_ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Majime {
            get {
                return ResourceManager.GetString("Voice_Majime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Masochist,Piston,0,H11_00673.ogg,H11_00673.ogg,
        ///Masochist,Piston,0,H11_00674.ogg,H11_00674.ogg,
        ///Masochist,Piston,0,H11_adult_05624.ogg,H11_adult_05624.ogg,
        ///Masochist,Piston,0,H11_adult_05625.ogg,H11_adult_05625.ogg,
        ///Masochist,Piston,1,H11_00675.ogg,H11_00675.ogg,
        ///Masochist,Piston,1,H11_00676.ogg,H11_00676.ogg,
        ///Masochist,Piston,1,H11_adult_05626.ogg,H11_adult_05626.ogg,
        ///Masochist,Piston,1,H11_adult_05627.ogg,H11_adult_05627.ogg,
        ///Masochist,Pi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Masochist {
            get {
                return ResourceManager.GetString("Voice_Masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Missy,Piston,0,H9_00570.ogg,H9_00786.ogg,
        ///Missy,Piston,0,H9_00571.ogg,H9_00787.ogg,
        ///Missy,Piston,0,H9_adult_55306.ogg,H9_adult_55522.ogg,
        ///Missy,Piston,0,H9_adult_55307.ogg,H9_adult_55523.ogg,
        ///Missy,Piston,1,H9_00572.ogg,H9_00788.ogg,
        ///Missy,Piston,1,H9_00573.ogg,H9_00789.ogg,
        ///Missy,Piston,1,H9_adult_55308.ogg,H9_adult_55524.ogg,
        ///Missy,Piston,1,H9_adult_55309.ogg,H9_adult_55525.ogg,
        ///Missy,Piston,2,H9_00574.ogg,H9_00790.ogg,
        ///Missy,Piston,2,H9 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Missy {
            get {
                return ResourceManager.GetString("Voice_Missy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Muku,Piston,0,H0_00053.ogg,H0_00229.ogg,
        ///Muku,Piston,0,H0_00054.ogg,H0_00230.ogg,
        ///Muku,Piston,0,H0_09210.ogg,H0_00229.ogg,
        ///Muku,Piston,0,H0_09211.ogg,H0_00230.ogg,
        ///Muku,Piston,0,H0_adult_61041.ogg,H0_adult_61257.ogg,
        ///Muku,Piston,0,H0_adult_61042.ogg,H0_adult_61258.ogg,
        ///Muku,Piston,1,H0_00055.ogg,H0_00231.ogg,
        ///Muku,Piston,1,H0_00056.ogg,H0_00232.ogg,
        ///Muku,Piston,1,H0_09212.ogg,H0_00231.ogg,
        ///Muku,Piston,1,H0_09213.ogg,H0_00232.ogg,
        ///Muku,Pis [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Muku {
            get {
                return ResourceManager.GetString("Voice_Muku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Pride,Piston,0,S0_01236.ogg,S0_103950.ogg,
        ///Pride,Piston,0,S0_01237.ogg,S0_103951.ogg,
        ///Pride,Piston,0,S0_adult_54259.ogg,S0_adult_54475.ogg,
        ///Pride,Piston,0,S0_adult_54260.ogg,S0_adult_54476.ogg,
        ///Pride,Piston,1,S0_01238.ogg,S0_103952.ogg,
        ///Pride,Piston,1,S0_01239.ogg,S0_103953.ogg,
        ///Pride,Piston,1,S0_adult_54261.ogg,S0_adult_54477.ogg,
        ///Pride,Piston,1,S0_adult_54262.ogg,S0_adult_54478.ogg,
        ///Pride,Piston,2,S0_01240.ogg,S0_103954.ogg,
        ///Pride,Piston [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Pride {
            get {
                return ResourceManager.GetString("Voice_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Pure,Piston,0,S2_01150.ogg,S2_104161.ogg,
        ///Pure,Piston,0,S2_01151.ogg,S2_104162.ogg,
        ///Pure,Piston,0,S2_adult_54334.ogg,S2_adult_54550.ogg,
        ///Pure,Piston,0,S2_adult_54335.ogg,S2_adult_54551.ogg,
        ///Pure,Piston,1,S2_01152.ogg,S2_104163.ogg,
        ///Pure,Piston,1,S2_01153.ogg,S2_104164.ogg,
        ///Pure,Piston,1,S2_adult_54336.ogg,S2_adult_54552.ogg,
        ///Pure,Piston,1,S2_adult_54337.ogg,S2_adult_54553.ogg,
        ///Pure,Piston,2,S2_01154.ogg,S2_104165.ogg,
        ///Pure,Piston,2,S2_0115 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Pure {
            get {
                return ResourceManager.GetString("Voice_Pure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Rindere,Piston,0,H2_00027.ogg,H2_00203.ogg,
        ///Rindere,Piston,0,H2_00028.ogg,H2_00204.ogg,
        ///Rindere,Piston,0,H2_09827.ogg,H2_00203.ogg,
        ///Rindere,Piston,0,H2_09828.ogg,H2_00204.ogg,
        ///Rindere,Piston,0,H2_adult_60549.ogg,H2_adult_60764.ogg,
        ///Rindere,Piston,0,H2_adult_60548.ogg,H2_adult_60765.ogg,
        ///Rindere,Piston,1,H2_00029.ogg,H2_00205.ogg,
        ///Rindere,Piston,1,H2_00030.ogg,H2_00206.ogg,
        ///Rindere,Piston,1,H2_09829.ogg,H2_00205.ogg,
        ///Rindere,Piston,1,H2_098 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Rindere {
            get {
                return ResourceManager.GetString("Voice_Rindere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Sadist,Piston,0,S6_02179.ogg,S6_102978.ogg,
        ///Sadist,Piston,0,S6_02180.ogg,S6_102979.ogg,
        ///Sadist,Piston,0,S6_adult_53633.ogg,S6_adult_53849.ogg,
        ///Sadist,Piston,0,S6_adult_53634.ogg,S6_adult_53850.ogg,
        ///Sadist,Piston,1,S6_02181.ogg,S6_102980.ogg,
        ///Sadist,Piston,1,S6_02182.ogg,S6_102981.ogg,
        ///Sadist,Piston,1,S6_adult_53635.ogg,S6_adult_53851.ogg,
        ///Sadist,Piston,1,S6_adult_53636.ogg,S6_adult_53852.ogg,
        ///Sadist,Piston,2,S6_02183.ogg,S6_102982.ogg,
        ///Sad [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Sadist {
            get {
                return ResourceManager.GetString("Voice_Sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Secretary,Piston,0,H6_00158.ogg,H6_00374.ogg,
        ///Secretary,Piston,0,H6_00159.ogg,H6_00375.ogg,
        ///Secretary,Piston,0,H6_adult_55951.ogg,H6_adult_56167.ogg,
        ///Secretary,Piston,0,H6_adult_55952.ogg,H6_adult_56168.ogg,
        ///Secretary,Piston,1,H6_00160.ogg,H6_00376.ogg,
        ///Secretary,Piston,1,H6_00161.ogg,H6_00377.ogg,
        ///Secretary,Piston,1,H6_adult_55953.ogg,H6_adult_56169.ogg,
        ///Secretary,Piston,1,H6_adult_55954.ogg,H6_adult_56170.ogg,
        ///Secretary,Piston,2,H6_00162. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Secretary {
            get {
                return ResourceManager.GetString("Voice_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Silent,Piston,0,H3_00518.ogg,H3_00734.ogg,
        ///Silent,Piston,0,H3_00519.ogg,H3_00735.ogg,
        ///Silent,Piston,0,H3_adult_55399.ogg,H3_adult_55615.ogg,
        ///Silent,Piston,0,H3_adult_55400.ogg,H3_adult_55616.ogg,
        ///Silent,Piston,1,H3_00520.ogg,H3_00736.ogg,
        ///Silent,Piston,1,H3_00521.ogg,H3_00737.ogg,
        ///Silent,Piston,1,H3_adult_55401.ogg,H3_adult_55617.ogg,
        ///Silent,Piston,1,H3_adult_55402.ogg,H3_adult_55618.ogg,
        ///Silent,Piston,2,H3_00522.ogg,H3_00738.ogg,
        ///Silent,P [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Silent {
            get {
                return ResourceManager.GetString("Voice_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Sister,Piston,0,H7_02762.ogg,H7_02978.ogg,
        ///Sister,Piston,0,H7_02763.ogg,H7_02979.ogg,
        ///Sister,Piston,0,H7_adult_55859.ogg,H7_adult_56075.ogg,
        ///Sister,Piston,0,H7_adult_55860.ogg,H7_adult_56076.ogg,
        ///Sister,Piston,1,H7_02764.ogg,H7_02980.ogg,
        ///Sister,Piston,1,H7_02765.ogg,H7_02981.ogg,
        ///Sister,Piston,1,H7_adult_55861.ogg,H7_adult_56077.ogg,
        ///Sister,Piston,1,H7_adult_55862.ogg,H7_adult_56078.ogg,
        ///Sister,Piston,2,H7_02766.ogg,H7_02982.ogg,
        ///Sister,P [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Sister {
            get {
                return ResourceManager.GetString("Voice_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,MotionType,ExcitementLevel,Normal,Estrus,dummy
        ///Yandere,Piston,0,S3_02687.ogg,S3_101125.ogg,
        ///Yandere,Piston,0,S3_02688.ogg,S3_101126.ogg,
        ///Yandere,Piston,0,S3_adult_54202.ogg,S3_adult_54418.ogg,
        ///Yandere,Piston,0,S3_adult_54203.ogg,S3_adult_54419.ogg,
        ///Yandere,Piston,1,S3_02689.ogg,S3_101127.ogg,
        ///Yandere,Piston,1,S3_02690.ogg,S3_101128.ogg,
        ///Yandere,Piston,1,S3_adult_54204.ogg,S3_adult_54420.ogg,
        ///Yandere,Piston,1,S3_adult_54205.ogg,S3_adult_54421.ogg,
        ///Yandere,Piston,2,S3_02691.ogg,S3_101129. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Voice_Yandere {
            get {
                return ResourceManager.GetString("Voice_Yandere", resourceCulture);
            }
        }
    }
}
